package Modifica;




import Afegir.Afegir_arma;
import Afegir.Afegir_adreça;
import Afegir.Afegir_adreça;
import Afegir.Afegir_antecedent;
import Afegir.Afegir_arma;
import Afegir.Afegir_moto;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramon Trilla Urteaga i Joan Francesc Pedro García
 */
public class Modificar_personal extends javax.swing.JDialog {

    /**
     * Creates new form Info_personal
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    public int member_id_creat;
    
    Veure_m_Usuaris pare;
    public Modificar_personal(Veure_m_Usuaris parent,boolean modal, Connection a, String id_user) {
        super(parent, modal);
        initComponents();
        con = a;
        pare = parent;
        member_id_creat = Integer.valueOf(id_user);
        update_tables();
        
        update_moto();
        update_guns();
        update_antecedents();
        posa_info();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        nom_textfield = new javax.swing.JTextField();
        cognom_textfield = new javax.swing.JTextField();
        sobrenom_textfield = new javax.swing.JTextField();
        sex_jComboBox = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        moto_jList = new javax.swing.JList<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        guns_jList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        antecedents_jList = new javax.swing.JList<>();
        afegir_moto = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        finalitzar_jButton = new javax.swing.JButton();
        eliminar_moto = new javax.swing.JButton();
        eliminar_guns = new javax.swing.JButton();
        eliminar_crime = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        date_jFormattedTextField1 = new javax.swing.JFormattedTextField();
        address_jcombobox = new javax.swing.JComboBox<>();
        Afegir_adreça = new javax.swing.JButton();
        seu_combobox = new javax.swing.JComboBox<>();
        Afegir_button = new javax.swing.JButton();
        banda_jCheckBox1 = new javax.swing.JCheckBox();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Nom:");

        jLabel4.setText("Sexe:");

        jLabel11.setText("Cognom:");

        jLabel13.setText("Sobrenom:");

        nom_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nom_textfieldKeyReleased(evt);
            }
        });

        cognom_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cognom_textfieldKeyReleased(evt);
            }
        });

        sobrenom_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                sobrenom_textfieldKeyReleased(evt);
            }
        });

        sex_jComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                        .addComponent(sex_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nom_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(sobrenom_textfield)
                            .addComponent(cognom_textfield))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nom_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(cognom_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(sobrenom_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(sex_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imatges/user_icon_176933.png"))); // NOI18N

        jLabel3.setText("Motocicletes:");

        jScrollPane1.setViewportView(moto_jList);

        jLabel8.setText("Armes:");

        jLabel9.setText("Antecedents");

        jScrollPane3.setViewportView(guns_jList);

        jScrollPane2.setViewportView(antecedents_jList);

        afegir_moto.setText("Afegir");
        afegir_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegir_motoActionPerformed(evt);
            }
        });

        jButton4.setText("Afegir");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Afegir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        finalitzar_jButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        finalitzar_jButton.setText("Finalitzar");
        finalitzar_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalitzar_jButtonActionPerformed(evt);
            }
        });

        eliminar_moto.setText("Eliminar");
        eliminar_moto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_motoActionPerformed(evt);
            }
        });

        eliminar_guns.setText("Eliminar");
        eliminar_guns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_gunsActionPerformed(evt);
            }
        });

        eliminar_crime.setText("Eliminar");
        eliminar_crime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_crimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(finalitzar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 319, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(afegir_moto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminar_moto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminar_guns, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(eliminar_crime, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane2)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(afegir_moto)
                        .addComponent(eliminar_moto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jButton4)
                    .addComponent(eliminar_guns))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jButton6)
                    .addComponent(eliminar_crime))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(finalitzar_jButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel1.setText("Data de neixament:");

        jLabel15.setText("Adreça:");

        jLabel17.setText("Pertany a SOA:");

        jLabel19.setText("Seu de referencia:");

        date_jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        date_jFormattedTextField1.setText("yyyy-mm-dd");
        date_jFormattedTextField1.setToolTipText("");

        address_jcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        address_jcombobox.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                address_jcomboboxMouseEntered(evt);
            }
        });

        Afegir_adreça.setText("Afegir");
        Afegir_adreça.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Afegir_adreçaActionPerformed(evt);
            }
        });

        seu_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        seu_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seu_comboboxActionPerformed(evt);
            }
        });

        Afegir_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Afegir_button.setText("Modificar");
        Afegir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Afegir_buttonActionPerformed(evt);
            }
        });

        banda_jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banda_jCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Afegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(seu_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(date_jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(address_jcombobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(247, 247, 247)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Afegir_adreça, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(banda_jCheckBox1))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addComponent(date_jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(address_jcombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Afegir_adreça))
                        .addGap(14, 14, 14)
                        .addComponent(jLabel17))
                    .addComponent(banda_jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(seu_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(Afegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(68, 68, 68))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finalitzar_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalitzar_jButtonActionPerformed
        JOptionPane.showMessageDialog(this, "Afegit correctament!", "Status", JOptionPane.INFORMATION_MESSAGE);
        pare.cerca_base_dades();
        this.dispose();
    }//GEN-LAST:event_finalitzar_jButtonActionPerformed

    private void Afegir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afegir_buttonActionPerformed
        afegir_persona();
        member_id_creat = get_moteroid();
        finalitzar_jButton.setEnabled(true);
    }//GEN-LAST:event_Afegir_buttonActionPerformed

    private void Afegir_adreçaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Afegir_adreçaActionPerformed
        Afegir_adreça h = new Afegir_adreça(this, true, con, false);
        h.setVisible(true);
    }//GEN-LAST:event_Afegir_adreçaActionPerformed

    private void address_jcomboboxMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_address_jcomboboxMouseEntered
        update_address();
    }//GEN-LAST:event_address_jcomboboxMouseEntered

    private void seu_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seu_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seu_comboboxActionPerformed

    private void banda_jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banda_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_banda_jCheckBox1ActionPerformed

    private void afegir_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegir_motoActionPerformed
        Afegir_moto h = new Afegir_moto(this, true, con, member_id_creat);
        h.setVisible(true);
    }//GEN-LAST:event_afegir_motoActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Afegir_arma h = new Afegir_arma(this, true, con, member_id_creat);
        h.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Afegir_antecedent h = new Afegir_antecedent(this, true, con, member_id_creat);
        h.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void nom_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nom_textfieldKeyReleased
        if (nom_textfield.getText().isBlank()){
            nom_textfield.setBackground(Color.red);
        }
        else{
            nom_textfield.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_nom_textfieldKeyReleased

    private void cognom_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cognom_textfieldKeyReleased
        if (cognom_textfield.getText().isBlank()){
            cognom_textfield.setBackground(Color.red);
        }
        else{
            cognom_textfield.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_cognom_textfieldKeyReleased

    private void sobrenom_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sobrenom_textfieldKeyReleased
        if (sobrenom_textfield.getText().isBlank()){
            sobrenom_textfield.setBackground(Color.red);
        }
        else{
            sobrenom_textfield.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_sobrenom_textfieldKeyReleased

    private void eliminar_motoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_motoActionPerformed
        Eliminar.Eliminar_moto h = new Eliminar.Eliminar_moto(this,con,true);
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_eliminar_motoActionPerformed

    private void eliminar_gunsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_gunsActionPerformed
        Eliminar.Eliminar_arma h = new Eliminar.Eliminar_arma(this,con,true);
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_eliminar_gunsActionPerformed

    private void eliminar_crimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_crimeActionPerformed
        Eliminar.Eliminar_delicte h = new Eliminar.Eliminar_delicte(this,con,true);
        h.setLocationRelativeTo(null);
        h.setVisible(true);
    }//GEN-LAST:event_eliminar_crimeActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Afegir_adreça;
    private javax.swing.JButton Afegir_button;
    private javax.swing.JComboBox<String> address_jcombobox;
    private javax.swing.JButton afegir_moto;
    private javax.swing.JList<String> antecedents_jList;
    private javax.swing.JCheckBox banda_jCheckBox1;
    private javax.swing.JTextField cognom_textfield;
    private javax.swing.JFormattedTextField date_jFormattedTextField1;
    private javax.swing.JButton eliminar_crime;
    private javax.swing.JButton eliminar_guns;
    private javax.swing.JButton eliminar_moto;
    private javax.swing.JButton finalitzar_jButton;
    private javax.swing.JList<String> guns_jList;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JList<String> moto_jList;
    private javax.swing.JTextField nom_textfield;
    private javax.swing.JComboBox<String> seu_combobox;
    private javax.swing.JComboBox<String> sex_jComboBox;
    private javax.swing.JTextField sobrenom_textfield;
    // End of variables declaration//GEN-END:variables
    
    
    private ResultSet executeQuery (Connection con, String query){
        
        try {
        
            stmt = con.createStatement();
            
            rs = stmt.executeQuery(query);           
            
            return rs;
        
        } catch (SQLException e){
          
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
            
            return null;
        }
    }
    
    public void update_address(){
        ResultSet result = executeQuery(con, "SELECT addressid,street,number,city,state,country from address;");            
        loadBranches(result, address_jcombobox);
    }
    public void consulta_seu(){
        ResultSet result = executeQuery(con, "SELECT headquarterid,headquartername, foundation from headquarters;");            
        loadBranches(result, seu_combobox);
    }
    
    
    private void loadBranches(ResultSet rs_o, javax.swing.JComboBox<String> in ){       
        in.removeAllItems();
        
        try {
            ResultSetMetaData rsmd = rs_o.getMetaData();
            int columnas = rsmd.getColumnCount();
            while ( rs_o.next() ) {  
                String result = "";
                for (int i = 1; i < columnas; i++){
                    result = result+rs_o.getString(i)+", ";
                }
                result = result+rs_o.getString(columnas);
               in.addItem(result);                        
               
            }
            
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }
    
    private void update_tables(){
        update_address();
        consulta_seu();        
    }
    
    
    
    
    
    private void afegir_persona(){
        String sql = "UPDATE members SET "+
                       
                "firstname = '" + nom_textfield.getText() + "'"
                
                + "," + 
                
                "lastname ='" + cognom_textfield.getText() + "'"
                
                + "," +
                
                "nickname ='" + sobrenom_textfield.getText() + "'"
                
                + "," +
                
                "sex ='" + sex_jComboBox.getSelectedItem() + "'"
                
                + "," +
                
                "birthday ='" + date_jFormattedTextField1.getText() + "'"
                
                + "," +
                
                "addressid ="+get_adress_id()+" "
                
                + "," +
                
                "inband ="+banda_jCheckBox1.isSelected()+" "
                
                + "," +
                
                "headquarterid ="+get_headquarter_id() +
                
                "WHERE memberid = "+member_id_creat+";";
        
        System.out.println(sql);
        try {
            
            stmt = con.createStatement();          
        
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(this, "S'ha afegit correctament!", "Status", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException e){
            
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);           
            
        }
    }
    
    private int get_headquarter_id(){
        StringTokenizer h = new StringTokenizer(seu_combobox.getSelectedItem().toString(), ",");
        return Integer.valueOf(h.nextToken());
    }
    private int get_adress_id(){
        StringTokenizer h = new StringTokenizer(address_jcombobox.getSelectedItem().toString(), ",");
        return Integer.valueOf(h.nextToken());
    }
    
    
    private int get_moteroid(){
        String consulta = "SELECT memberid FROM members WHERE "
  
                +"firstname='"+nom_textfield.getText()+"' AND "+
                "lastname='"+cognom_textfield.getText()+"'"+
                ";";
                
        System.out.println(consulta);
        ResultSet result = executeQuery(con, consulta);
        try{
            result.next();
            System.out.println(result.getInt(1));
            return (result.getInt(1));
        }catch (SQLException e){
            return 0;
        }
        
    }
    
    public void update_moto(){
        String consulta = "SELECT licenseplate, brand, model FROM bikes WHERE memberid = '"+ member_id_creat+"';";
        update_list(moto_jList,consulta);
    }
    
    public void update_guns(){
        String consulta = "SELECT brand, model FROM guns WHERE memberid = '"+ member_id_creat+"';";
        update_list(guns_jList,consulta);
    }
    public void update_antecedents(){
        String consulta = "SELECT crime, jurydate,jailin,jailout FROM criminalrecord WHERE memberid = '"+ member_id_creat+"';";
        update_list(antecedents_jList,consulta);
        
    }
    
    private void update_list(javax.swing.JList<String> in, String consulta){
        ResultSet result = executeQuery(con, consulta);
        DefaultListModel model = new DefaultListModel();
        
        model.clear();
        
        try {
            
            while ( result.next() ) {
                String out = "";
                ResultSetMetaData rsmd = result.getMetaData();
                int columnas = rsmd.getColumnCount();
                for (int i = 1; i < columnas; i++){
                    out = out+result.getString(i)+", ";
                }
                out = out+result.getString(columnas);
                model.addElement(out);  
            }
               
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
        
        in.setModel(model);
    }
    
    private void comprovar(){
        Afegir_button.setEnabled(revisar());
    }
    private boolean revisar(){
        if (nom_textfield.getText().isBlank()){
            return false;
        }
        
        if (cognom_textfield.getText().isBlank()){
            return false;
        }
        
        if (sobrenom_textfield.getText().isBlank()){
            return false;
        }
        return true;
    }
    
    private void posa_info(){
        String consulta = "SELECT * FROM members WHERE memberid = "+member_id_creat+";";
        ResultSet result = executeQuery(con, consulta);
        int ad = 0;
        int hq = 0;
        try {
            result.next();
            nom_textfield.setText(result.getString(2));
            cognom_textfield.setText(result.getString(3));
            sobrenom_textfield.setText(result.getString(4));
            sex_jComboBox.setSelectedItem(result.getString(5));
            date_jFormattedTextField1.setText(result.getString(6));
            ad = result.getInt(7);
            banda_jCheckBox1.setSelected(result.getBoolean(8));
            hq = result.getInt(9);
        } catch (SQLException e){
            
        }
        /*
        try{
        consulta = "SELECT addressid,street,number,city,state,country from address WHERE addressid = "+ad+";";
        result = executeQuery(con, consulta);
        result.next();
        String sel = "";
        for (int i = 0; i < 5; i++){
            sel = sel + result.getString(i)+", ";
        }
        sel = sel + result.getString(5);
        System.out.println(sel);
        address_jcombobox.setSelectedItem(sel);
        } catch (SQLException e){
        }
        
        try{
        consulta = "SELECT headquarterid,headquartername, foundation from headquarters WHERE headquarterid = "+hq+";";
        result = executeQuery(con, consulta);
        result.next();
        seu_combobox.setSelectedItem(result.toString());
        } catch (SQLException e){
        }
        */
    }
}
