package Veure;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import javax.swing.DefaultListModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramon Trilla Urteaga i Joan Francesc Pedro García
 */
public class Veure_Antecedents extends javax.swing.JDialog {

    /**
     * Creates new form Veure_Usuaris
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    java.awt.Frame pare;
    
    String search_id = "";
    String search_nom = "";
    String search_delicte = "";
    String search_estat = "";
    
    public Veure_Antecedents(java.awt.Frame parent, Connection c, boolean modal, boolean super_u) {
        super(parent, modal);
        initComponents();
        con = c;
        pare = parent;
        afegir_button.setEnabled(super_u);
        eliminar_button1.setEnabled(super_u);
        cerca_base_dades();
        update_nom();
        //update_delicte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nom_combo = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        delicte_combo = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        eliminar_button1 = new javax.swing.JButton();
        afegir_button = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Buscar:");

        jLabel2.setText("Nom:");

        nom_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tots" }));
        nom_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                nom_comboItemStateChanged(evt);
            }
        });
        nom_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_comboActionPerformed(evt);
            }
        });

        jLabel3.setText("Delicte:");

        delicte_combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tots" }));
        delicte_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                delicte_comboItemStateChanged(evt);
            }
        });
        delicte_combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delicte_comboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nom_combo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delicte_combo, 0, 190, Short.MAX_VALUE))
                .addContainerGap(210, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nom_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(delicte_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jList1MouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jList1MousePressed(evt);
            }
        });
        jList1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jList1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jList1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        eliminar_button1.setText("Eliminar");
        eliminar_button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminar_button1ActionPerformed(evt);
            }
        });

        afegir_button.setText("Afegir");
        afegir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                afegir_buttonActionPerformed(evt);
            }
        });

        jButton1.setText("Tancar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(eliminar_button1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(afegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(eliminar_button1)
                            .addComponent(afegir_button))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jList1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MousePressed
        /*
        String seleccionat = jList1.getSelectedValue();
        
        System.out.println(seleccionat);
        */
    }//GEN-LAST:event_jList1MousePressed

    private void jList1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseEntered
        
        
    }//GEN-LAST:event_jList1MouseEntered

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        String seleccionat = jList1.getSelectedValue();
        StringTokenizer st = new StringTokenizer(seleccionat,",");
        st.nextToken();
        String a_buscar = st.nextToken();
        Info.Info_Delicte h = new Info.Info_Delicte(pare, a_buscar, true, con);
        h.setVisible(true);
    }//GEN-LAST:event_jList1MouseClicked

    private void jList1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyTyped
       
    }//GEN-LAST:event_jList1KeyTyped

    private void jList1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jList1KeyReleased
       
    }//GEN-LAST:event_jList1KeyReleased

    private void afegir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_afegir_buttonActionPerformed
        Afegir.Afegir_antecedent h = new Afegir.Afegir_antecedent(this, true, con);
        h.setVisible(true);
    }//GEN-LAST:event_afegir_buttonActionPerformed

    private void eliminar_button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminar_button1ActionPerformed
        Eliminar.Eliminar_delicte h = new Eliminar.Eliminar_delicte(this, con, true);
        h.setVisible(true);
    }//GEN-LAST:event_eliminar_button1ActionPerformed

    private void delicte_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delicte_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_delicte_comboActionPerformed

    private void nom_comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_comboActionPerformed
        
    }//GEN-LAST:event_nom_comboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nom_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_nom_comboItemStateChanged
        busqueda();
    }//GEN-LAST:event_nom_comboItemStateChanged

    private void delicte_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_delicte_comboItemStateChanged
        busqueda();
    }//GEN-LAST:event_delicte_comboItemStateChanged

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton afegir_button;
    private javax.swing.JComboBox<String> delicte_combo;
    private javax.swing.JButton eliminar_button1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> nom_combo;
    // End of variables declaration//GEN-END:variables
    
    //todo
    private void busqueda(){
        String a;
        if (nom_combo.getSelectedItem().equals("Tots") && delicte_combo.getSelectedItem().equals("Tots")){
            a = "SELECT * from veure_antecedents;";
        }
        else if (!nom_combo.getSelectedItem().equals("Tots") && delicte_combo.getSelectedItem().equals("Tots")){
            StringTokenizer st = new StringTokenizer(nom_combo.getSelectedItem().toString(),",");
            String no = st.nextToken();
            String co = st.nextToken();
            co = co.substring(1);
            a = "SELECT * from veure_antecedents WHERE firstname ='"+no+"' AND lastname ='"+co+"';";
        }
        else if (nom_combo.getSelectedItem().equals("Tots") && !delicte_combo.getSelectedItem().equals("Tots")){
            a = "SELECT * from veure_antecedents WHERE crime ='"+delicte_combo.getSelectedItem()+"';";
        }
        else{
            StringTokenizer st = new StringTokenizer(nom_combo.getSelectedItem().toString(),",");
            String no = st.nextToken();
            String co = st.nextToken();
            a = "SELECT * from veure_antecedents WHERE (firstname ='"+no+"' AND lastname ='"+co+"') AND crime='"+delicte_combo.getSelectedItem()+";";
        }
        
        System.out.println(a);
        ResultSet result = executeQuery(con, a);            
        loadBranches(result);
    }
    
    public void cerca_base_dades(){
        ResultSet result = executeQuery(con, "SELECT * from veure_antecedents;");            
        loadBranches(result);
        update_delicte();
        
    }
    
    private void loadBranches(ResultSet branches){
        
        DefaultListModel model = new DefaultListModel();
        
        model.clear();
        
        try {
            while (branches.next()) {            
            
                String license = rs.getString(1);
                String brand = rs.getString(2);
                String model_b = rs.getString(3);
                String motor = rs.getString(4);
                String motor2 = rs.getString(5);               
                String result = license + " " +brand + "," + model_b + "," + motor+","+ motor2;
                model.addElement(result);                       
               
                                         
               
            }
            
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
        
        this.jList1.setModel(model);
    }
    
    private ResultSet executeQuery (Connection con, String query){
        
        try {
        
            stmt = con.createStatement();
            
            rs = stmt.executeQuery(query);           
            
            return rs;
        
        } catch (SQLException e){
          
            //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
            
            return null;
        }
    }
    
    private void update_nom(){
        ResultSet res = executeQuery(con, "SELECT firstname, lastname FROM members;");
        updateBranches(res,nom_combo);
    }
    
    private void update_delicte(){
        ResultSet res = executeQuery(con, "SELECT DISTINCT crime FROM criminalrecord;");
        updateBranches(res,delicte_combo);
    }
    
    private void updateBranches(ResultSet rs_o, javax.swing.JComboBox<String> in ){       
        try {
            ResultSetMetaData rsmd = rs_o.getMetaData();
            int columnas = rsmd.getColumnCount();
            while ( rs_o.next() ) {  
                String result = "";
                for (int i = 1; i < columnas; i++){
                    result = result+rs_o.getString(i)+", ";
                }
                result = result+rs_o.getString(columnas);
               in.addItem(result);                        
               
            }  
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    
}   
