package Afegir;




import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramon Trilla Urteaga i Joan Francesc Pedro García
 */
public class Afegir_antecedent extends javax.swing.JDialog {

    
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    private int member_id = 0;
    Afegir_personal pare_dia = null;
    Veure.Veure_Antecedents pare_v = null;
    Modifica.Modificar_personal pare_m = null;
    
    public Afegir_antecedent(Veure.Veure_Antecedents parent, boolean modal, Connection a) {
        super(parent, modal);
        initComponents();
        con = a;
        pare_v = parent;
        carrega_propietari();
        affegir_button.setEnabled(false);
    }
    
    public Afegir_antecedent(Afegir_personal parent, boolean modal, Connection a, int id) {
        super(parent, modal);
        initComponents();
        con = a;
        member_id = id;
        propietari_combobox.removeAllItems();
        propietari_combobox.addItem(String.valueOf(member_id));
        propietari_combobox.setEnabled(false);
        pare_dia = parent;
        affegir_button.setEnabled(false);
    }
    
    public Afegir_antecedent(Modifica.Modificar_personal parent, boolean modal, Connection a, int id) {
        super(parent, modal);
        initComponents();
        con = a;
        member_id = id;
        propietari_combobox.removeAllItems();
        propietari_combobox.addItem(String.valueOf(member_id));
        propietari_combobox.setEnabled(false);
        pare_m = parent;
        affegir_button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        propietari_combobox = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        criml_textfield = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        affegir_button = new javax.swing.JButton();
        jury_text = new javax.swing.JFormattedTextField();
        in_text = new javax.swing.JFormattedTextField();
        out_text = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Membre:");

        jLabel4.setText("Entrada a presó:");

        jLabel13.setText("Dia del judici:");

        propietari_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Error" }));
        propietari_combobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietari_comboboxActionPerformed(evt);
            }
        });

        jLabel14.setText("Crim:");

        criml_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                criml_textfieldKeyReleased(evt);
            }
        });

        jLabel5.setText("Sortida de presó:");

        affegir_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        affegir_button.setText("Afegir");
        affegir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affegir_buttonActionPerformed(evt);
            }
        });

        jury_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        jury_text.setText("yyyy-MM-dd");
        jury_text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jury_textActionPerformed(evt);
            }
        });

        in_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        in_text.setText("yyyy-MM-dd");

        out_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        out_text.setText("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)
                        .addGap(194, 194, 194)
                        .addComponent(out_text, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(criml_textfield)
                                    .addComponent(propietari_combobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 300, Short.MAX_VALUE))
                                .addComponent(jury_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(in_text, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(propietari_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(criml_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jury_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(in_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(out_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imatges/handcuffs.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affegir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affegir_buttonActionPerformed
        afegir();
        if (pare_dia != null){
            pare_dia.update_antecedents();
  
        }
        else if (pare_v != null){
            pare_v.cerca_base_dades();
        }
        else{
            pare_m.update_antecedents();
        }
        this.dispose();
    }//GEN-LAST:event_affegir_buttonActionPerformed

    private void propietari_comboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietari_comboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propietari_comboboxActionPerformed

    private void criml_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_criml_textfieldKeyReleased
        if (criml_textfield.getText().isBlank()){
            criml_textfield.setBackground(Color.red);
            affegir_button.setEnabled(false);
        }
        else{
            criml_textfield.setBackground(Color.white);
            affegir_button.setEnabled(true);
        }
    }//GEN-LAST:event_criml_textfieldKeyReleased

    private void jury_textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jury_textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jury_textActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton affegir_button;
    private javax.swing.JTextField criml_textfield;
    private javax.swing.JFormattedTextField in_text;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField jury_text;
    private javax.swing.JFormattedTextField out_text;
    private javax.swing.JComboBox<String> propietari_combobox;
    // End of variables declaration//GEN-END:variables

    
    //funciona
    private void afegir(){
        String id = "";
        if (pare_v == null){
            id = "'" + propietari_combobox.getSelectedItem() + "'";
        } 
        else{
            id = get_m_id();
        }
        
        
        String sql = "INSERT INTO criminalrecord (memberid, crime, jurydate, jailin, jailout) "
        
                + "VALUES (" + 
                
                id
                    
                + "," +
                
                "'" + criml_textfield.getText() + "'"
                
                + "," +
                
                "'" + jury_text.getText() + "'"
                
                + "," +
                
                "'" + in_text.getText() + "'"
                
                + "," +
                                
                "'" + out_text.getText() + "'"+
                
                ");";
        
        System.out.println(sql);
        try {
            
            stmt = con.createStatement();          
        
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(this, "S'ha afegit correctament!", "Status", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException e){
            
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);           
            
        }
    }
    
    private void carrega_propietari(){
        ResultSet res = executeQuery(con, "SELECT memberid, firstname, lastname FROM members;");
        loadBranches(res,propietari_combobox);
    }
    
    private String get_m_id(){
        StringTokenizer st = new StringTokenizer(propietari_combobox.getSelectedItem().toString(),",");
        return st.nextToken();
    }
    
    
    private ResultSet executeQuery (Connection con, String query){
        
        try {
        
            stmt = con.createStatement();
            
            rs = stmt.executeQuery(query);           
            
            return rs;
        
        } catch (SQLException e){
          
            //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
            
            return null;
        }
    }
    
    private void loadBranches(ResultSet rs_o, javax.swing.JComboBox<String> in ){       
        in.removeAllItems();
        
        try {
            ResultSetMetaData rsmd = rs_o.getMetaData();
            int columnas = rsmd.getColumnCount();
            while ( rs_o.next() ) {  
                String result = "";
                for (int i = 1; i < columnas; i++){
                    result = result+rs_o.getString(i)+", ";
                }
                result = result+rs_o.getString(columnas);
               in.addItem(result);                        
               
            }  
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
    }
}
