package Afegir;




import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramon Trilla Urteaga i Joan Francesc Pedro García
 */
public class Afegir_moto extends javax.swing.JDialog {

    /**
     * Creates new form Info_personal
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    private int member_id = 0;
    Afegir_personal pare_dia = null;
    Veure.Veure_Motos pare_v = null;
    Modifica.Modificar_personal pare_m = null;
    
    public Afegir_moto(Veure.Veure_Motos parent, boolean modal, Connection a) {
        super(parent, modal);
        initComponents();
        con = a;
        pare_v = parent;
        carrega_propietari();
        affegir_button.setEnabled(false);
        
    }
    
    public Afegir_moto(Afegir_personal parent, boolean modal, Connection a, int id) {
        super(parent, modal);
        initComponents();
        con = a;
        member_id = id;
        propietari_combobox.removeAllItems();
        propietari_combobox.addItem(String.valueOf(member_id));
        propietari_combobox.setEnabled(false);
        pare_dia = parent;
        affegir_button.setEnabled(false);
    }
    
    public Afegir_moto(Modifica.Modificar_personal parent, boolean modal, Connection a, int id) {
        super(parent, modal);
        initComponents();
        con = a;
        member_id = id;
        propietari_combobox.removeAllItems();
        propietari_combobox.addItem(String.valueOf(member_id));
        propietari_combobox.setEnabled(false);
        pare_m = parent;
        affegir_button.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        matricula_textfield = new javax.swing.JTextField();
        model_textfield = new javax.swing.JTextField();
        propietari_combobox = new javax.swing.JComboBox<>();
        cilindrada_textfield = new javax.swing.JTextField();
        caballs_textfield = new javax.swing.JTextField();
        affegir_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        marcal_textfield = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Propietari:");

        jLabel4.setText("Cilindrada:");

        jLabel11.setText("Matricula:");

        jLabel13.setText("Model:");

        jLabel12.setText("Cavalls:");

        matricula_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                matricula_textfieldKeyReleased(evt);
            }
        });

        model_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                model_textfieldActionPerformed(evt);
            }
        });

        propietari_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Error" }));

        cilindrada_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cilindrada_textfieldKeyReleased(evt);
            }
        });

        caballs_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                caballs_textfieldKeyReleased(evt);
            }
        });

        affegir_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        affegir_button.setText("Afegir");
        affegir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affegir_buttonActionPerformed(evt);
            }
        });

        jLabel14.setText("Marca:");

        marcal_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                marcal_textfieldKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 338, Short.MAX_VALUE)
                        .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(marcal_textfield)
                            .addComponent(caballs_textfield)
                            .addComponent(cilindrada_textfield)
                            .addComponent(propietari_combobox, javax.swing.GroupLayout.Alignment.TRAILING, 0, 300, Short.MAX_VALUE)
                            .addComponent(matricula_textfield, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(model_textfield, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(propietari_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(matricula_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(marcal_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(model_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cilindrada_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(caballs_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imatges/bike-18_icon-icons.com_66445.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 35, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affegir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affegir_buttonActionPerformed
        afegir();
        if (pare_dia != null){
            pare_dia.update_moto();   
        }
        else if (pare_v != null){
            pare_v.cerca_base_dades();
        }
        else{
            pare_m.update_moto();
        }
        this.dispose();
    }//GEN-LAST:event_affegir_buttonActionPerformed

    private void matricula_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_matricula_textfieldKeyReleased
        if (matricula_textfield.getText().isBlank()){
            matricula_textfield.setBackground(Color.red);
        }
        else{
            matricula_textfield.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_matricula_textfieldKeyReleased

    private void marcal_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_marcal_textfieldKeyReleased
        if (marcal_textfield.getText().isBlank()){
            marcal_textfield.setBackground(Color.red);
        }
        else{
            marcal_textfield.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_marcal_textfieldKeyReleased

    private void model_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_model_textfieldActionPerformed
        if (model_textfield.getText().isBlank()){
            model_textfield.setBackground(Color.red);
        }
        else{
            model_textfield.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_model_textfieldActionPerformed

    private void cilindrada_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cilindrada_textfieldKeyReleased
        try {
            Integer.parseInt(cilindrada_textfield.getText());
            cilindrada_textfield.setBackground(Color.white);
        } catch (NumberFormatException excepcion) {
            cilindrada_textfield.setBackground(Color.red);
        }
        comprovar();
    }//GEN-LAST:event_cilindrada_textfieldKeyReleased

    private void caballs_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_caballs_textfieldKeyReleased
        try {
            Integer.parseInt(caballs_textfield.getText());
            caballs_textfield.setBackground(Color.white);
        } catch (NumberFormatException excepcion) {
            caballs_textfield.setBackground(Color.red);
        }
        comprovar();
    }//GEN-LAST:event_caballs_textfieldKeyReleased

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton affegir_button;
    private javax.swing.JTextField caballs_textfield;
    private javax.swing.JTextField cilindrada_textfield;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField marcal_textfield;
    private javax.swing.JTextField matricula_textfield;
    private javax.swing.JTextField model_textfield;
    private javax.swing.JComboBox<String> propietari_combobox;
    // End of variables declaration//GEN-END:variables

    
    //funciona
    private void afegir(){
        String a = "";
        
        if (pare_v == null){
            a = "'" + propietari_combobox.getSelectedItem() + "'";
        }
        else{
            StringTokenizer st = new StringTokenizer(propietari_combobox.getSelectedItem().toString(),",");
            a = st.nextToken();
        }
        
        
        String sql = "INSERT INTO bikes (licenseplate, brand, model, motor, memberid) "
        
                + "VALUES (" + 
                
                "'" + matricula_textfield.getText() + "'"
                
                + "," +
                
                "'" + marcal_textfield.getText() + "'"
                
                + "," +
                
                "'" + model_textfield.getText() + "'"
                
                + "," +
                
                "'" + cilindrada_textfield.getText()+" ("+caballs_textfield.getText() + ")'"
                
                + "," +
                                
                a+
                
                ");";
        
        System.out.println(sql);
        try {
            
            stmt = con.createStatement();          
        
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(this, "S'ha afegit correctament!", "Status", JOptionPane.INFORMATION_MESSAGE);
            
            
        } catch (SQLException e){
            
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);           
            
        }
    }
    
    private void carrega_propietari(){
        ResultSet res = executeQuery(con, "SELECT memberid, firstname, lastname FROM members;");
        loadBranches(res,propietari_combobox);
    }
    
    private ResultSet executeQuery (Connection con, String query){
        
        try {
        
            stmt = con.createStatement();
            
            rs = stmt.executeQuery(query);           
            
            return rs;
        
        } catch (SQLException e){
          
            //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
            
            return null;
        }
    }
    
    private void loadBranches(ResultSet rs_o, javax.swing.JComboBox<String> in ){       
        in.removeAllItems();
        
        try {
            ResultSetMetaData rsmd = rs_o.getMetaData();
            int columnas = rsmd.getColumnCount();
            while ( rs_o.next() ) {  
                String result = "";
                for (int i = 1; i < columnas; i++){
                    result = result+rs_o.getString(i)+", ";
                }
                result = result+rs_o.getString(columnas);
               in.addItem(result);                        
               
            }  
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private void comprovar(){
        affegir_button.setEnabled(revisar());
    }
    
    private boolean revisar(){
        if (matricula_textfield.getText().isBlank()){
            return false;
        }
        if (marcal_textfield.getText().isBlank()){
            return false;
        }
        if (model_textfield.getText().isBlank()){
            return false;
        }
        
        if (cilindrada_textfield.getText().isBlank()){
            return false;
        }
        if (!cilindrada_textfield.getText().isBlank()){
            try {
                int numero = Integer.parseInt(cilindrada_textfield.getText());
                
                if (1 > numero){
                    return false;
                }
            } catch (NumberFormatException e){
                return false;
            }
        }
        
        if (caballs_textfield.getText().isBlank()){
            return false;
        }
        if (!caballs_textfield.getText().isBlank()){
            try {
                int numero = Integer.parseInt(caballs_textfield.getText());
                
                if (1 > numero){
                    return false;
                }
            } catch (NumberFormatException e){
                return false;
            }
        }
        return true;
        
    }
}
