package Afegir;




import Afegir.Afegir_adreça_headquarter;
import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramon Trilla Urteaga i Joan Francesc Pedro García
 */
public class Afegir_adreça extends javax.swing.JDialog {

    /**
     * Creates new form Info_personal
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    Afegir_adreça_headquarter pare;
    
    
    public Afegir_adreça(Afegir_adreça_headquarter parent, boolean modal, Connection a) {
        super(parent, modal);
        initComponents();
        con = a;
        tipus_combobox.removeAllItems();
        tipus_combobox.addItem("Headquarter");
        pare = parent;
        affegir_button.setEnabled(false);
    }
    
    public Afegir_adreça(javax.swing.JDialog parent, boolean modal, Connection a, boolean only_charter) {
        super(parent, modal);
        initComponents();
        con = a;
        if (only_charter){
            tipus_combobox.removeAllItems();
            tipus_combobox.addItem("Headquarter");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        carrer_textfield = new javax.swing.JTextField();
        numero_textfield = new javax.swing.JTextField();
        tipus_combobox = new javax.swing.JComboBox<>();
        ciutat_textfield = new javax.swing.JTextField();
        pro_textfield = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        pais_textfield = new javax.swing.JTextField();
        affegir_button = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Tipus de edifici:");

        jLabel4.setText("Ciutat:");

        jLabel11.setText("Carrer:");

        jLabel13.setText("Numero:");

        jLabel12.setText("Província/estat:");

        carrer_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carrer_textfieldActionPerformed(evt);
            }
        });
        carrer_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                carrer_textfieldKeyReleased(evt);
            }
        });

        numero_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                numero_textfieldKeyReleased(evt);
            }
        });

        tipus_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "House", "Flat" }));

        ciutat_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ciutat_textfieldKeyReleased(evt);
            }
        });

        pro_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pro_textfieldKeyReleased(evt);
            }
        });

        jLabel14.setText("País:");

        pais_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pais_textfieldActionPerformed(evt);
            }
        });
        pais_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pais_textfieldKeyReleased(evt);
            }
        });

        affegir_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        affegir_button.setText("Afegir");
        affegir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affegir_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numero_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                            .addComponent(carrer_textfield)
                            .addComponent(tipus_combobox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(pro_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(99, 99, 99)
                        .addComponent(pais_textfield, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addComponent(ciutat_textfield))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tipus_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(carrer_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(numero_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(ciutat_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(pro_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(pais_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imatges/address-location.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affegir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affegir_buttonActionPerformed
        afegir();
        
        
    }//GEN-LAST:event_affegir_buttonActionPerformed

    private void carrer_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_carrer_textfieldKeyReleased
        if (carrer_textfield.getText().isBlank()){
            carrer_textfield.setBackground(Color.red);
        }
        else{
            carrer_textfield.setBackground(Color.WHITE);
        }
        comprova();
    }//GEN-LAST:event_carrer_textfieldKeyReleased

    private void carrer_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carrer_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_carrer_textfieldActionPerformed

    private void numero_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_numero_textfieldKeyReleased
        try {
            Integer.parseInt(numero_textfield.getText());
            numero_textfield.setBackground(Color.white);
        } catch (NumberFormatException excepcion) {
            numero_textfield.setBackground(Color.red);
        }
        comprova();
    }//GEN-LAST:event_numero_textfieldKeyReleased

    private void ciutat_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ciutat_textfieldKeyReleased
        if (ciutat_textfield.getText().isBlank()){
            ciutat_textfield.setBackground(Color.red);
        }
        else{
            ciutat_textfield.setBackground(Color.WHITE);
        }
        comprova();
    }//GEN-LAST:event_ciutat_textfieldKeyReleased

    private void pro_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pro_textfieldKeyReleased
        if (pro_textfield.getText().isBlank()){
            pro_textfield.setBackground(Color.red);
        }
        else{
            pro_textfield.setBackground(Color.WHITE);
        }
        comprova();
    }//GEN-LAST:event_pro_textfieldKeyReleased

    private void pais_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pais_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pais_textfieldActionPerformed

    private void pais_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pais_textfieldKeyReleased
        if (pais_textfield.getText().isBlank()){
            pais_textfield.setBackground(Color.red);
        }
        else{
            pais_textfield.setBackground(Color.WHITE);
        }
        comprova();
    }//GEN-LAST:event_pais_textfieldKeyReleased

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton affegir_button;
    private javax.swing.JTextField carrer_textfield;
    private javax.swing.JTextField ciutat_textfield;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField numero_textfield;
    private javax.swing.JTextField pais_textfield;
    private javax.swing.JTextField pro_textfield;
    private javax.swing.JComboBox<String> tipus_combobox;
    // End of variables declaration//GEN-END:variables

    
    //funciona
    private void afegir(){
        String sql = "INSERT INTO Address (type, street, number, city, state, country) "
        
                + "VALUES (" + 
                
                "'" + tipus_combobox.getSelectedItem() + "'"
                
                + "," + 
                
                "'" + carrer_textfield.getText() + "'"
                
                + "," +
                
                Integer.valueOf(numero_textfield.getText())
                
                + "," +
                
                "'" + ciutat_textfield.getText() + "'"
                
                + "," +
                
                "'" + pro_textfield.getText() + "'" 
                
                + "," +
                
                "'" + pais_textfield.getText() + "'" +
                
                ");";
        
        System.out.println(sql);
        try {
            
            stmt = con.createStatement();          
        
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(this, "S'ha afegit correctament!", "Status", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException e){
            
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);           
            
        }
        seteja_id_adressa(pare);
        this.dispose();
    }
    
    private void seteja_id_adressa(Afegir_adreça_headquarter in){
        String a = "SELECT * from address WHERE type='"+tipus_combobox.getSelectedItem()+
                "' AND street='"+carrer_textfield.getText()+
                "' AND number='"+Integer.valueOf(numero_textfield.getText())+
                "' AND city='"+ciutat_textfield.getText()+
                "' AND state='"+pro_textfield.getText()+
                "' AND country='"+pais_textfield.getText()+
                "';";
        ResultSet result = executeQuery(con, a);            
        try {
            result.next();
            in.adreça_id_enviada = result.getInt(1);
            String ad = result.getString(3)+", "+result.getInt(4)+", "+result.getString(5)+", "+result.getString(6)+", "+result.getString(7);
            System.out.println(ad);
            in.update_ad(ad);
           
        } catch (SQLException e){
            
        }
    }
    
    private void comprova(){
        affegir_button.setEnabled(es_factible());
    }
    
    private boolean es_factible(){
        
        //Comprovar carrer
        if (carrer_textfield.getText().isBlank()){
            return false;
        }
        
        //Comprovar numero
        if (numero_textfield.getText().isBlank()){
            return false;
        }
        if (!numero_textfield.getText().isBlank()){
            try {
                int numero = Integer.parseInt(numero_textfield.getText());
                
                if (1 > numero){
                    return false;
                }
            } catch (NumberFormatException e){
                return false;
            }
        }
        
        
               
        //Comprovar ciutat
        if (ciutat_textfield.getText().isBlank()){
            return false;
        }
        
        //Comprovar provincia/estat
        if (pro_textfield.getText().isBlank()){
            return false;
        }
        
        //Comprovar pais
        if (pais_textfield.getText().isBlank()){
            return false;
        }
        return true;
    }
    
    
    private ResultSet executeQuery (Connection con, String query){
        
        try {
        
            stmt = con.createStatement();
            
            rs = stmt.executeQuery(query);           
            
            return rs;
        
        } catch (SQLException e){
          
            //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
            
            return null;
        }
    }
}
