package Afegir;




import java.awt.Color;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Ramon Trilla Urteaga i Joan Francesc Pedro García
 */
public class Afegir_move extends javax.swing.JDialog {

    /**
     * Creates new form Info_personal
     */
    Connection con;
    public static Statement stmt = null;
    public static ResultSet rs = null;
    private boolean factible = false;
    
    Veure.Veure_Diners pare;
    
    public Afegir_move(Veure.Veure_Diners parent, boolean modal, Connection a) {
        super(parent, modal);
        initComponents();
        con = a;
        
        pare = parent;
        carregar_headquarters();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        head_combobox = new javax.swing.JComboBox<>();
        affegir_button = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        mov_textfield = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        descripcio_text = new javax.swing.JTextField();
        data_text = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel2.setText("Headquarter:");

        jLabel13.setText("Data:");

        head_combobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Error" }));

        affegir_button.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        affegir_button.setText("Afegir");
        affegir_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affegir_buttonActionPerformed(evt);
            }
        });

        jLabel14.setText("Moviment:");

        mov_textfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mov_textfieldActionPerformed(evt);
            }
        });
        mov_textfield.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mov_textfieldKeyReleased(evt);
            }
        });

        jLabel15.setText("Descripció:");

        descripcio_text.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                descripcio_textKeyReleased(evt);
            }
        });

        data_text.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyyy-MM-dd"))));
        data_text.setText("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 113, Short.MAX_VALUE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(descripcio_text)
                                    .addComponent(mov_textfield, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(head_combobox, 0, 300, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(213, 213, 213)
                                .addComponent(data_text, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)))))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(head_combobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(descripcio_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(mov_textfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(data_text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(affegir_button, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imatges/calculator-money.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void affegir_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affegir_buttonActionPerformed
        afegir();
        pare.cerca_base_dades();
        this.dispose();        
    }//GEN-LAST:event_affegir_buttonActionPerformed

    private void mov_textfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mov_textfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mov_textfieldActionPerformed

    private void descripcio_textKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_descripcio_textKeyReleased
        if (descripcio_text.getText().isBlank()){
            descripcio_text.setBackground(Color.red);
        }
        else{
            descripcio_text.setBackground(Color.white);
        }
        comprovar();
    }//GEN-LAST:event_descripcio_textKeyReleased

    private void mov_textfieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mov_textfieldKeyReleased
        try {
            Integer.parseInt(mov_textfield.getText());
            mov_textfield.setBackground(Color.white);
        } catch (NumberFormatException excepcion) {
            mov_textfield.setBackground(Color.red);
        }
        comprovar();
    }//GEN-LAST:event_mov_textfieldKeyReleased

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton affegir_button;
    private javax.swing.JFormattedTextField data_text;
    private javax.swing.JTextField descripcio_text;
    private javax.swing.JComboBox<String> head_combobox;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField mov_textfield;
    // End of variables declaration//GEN-END:variables

    
    //funciona
    private void afegir(){
        int id;
        StringTokenizer st = new StringTokenizer(head_combobox.getSelectedItem().toString(),",");
        id = Integer.valueOf(st.nextElement().toString());
        String sql = "INSERT INTO moves (headquarterid, movedesc, date, deposit) "
        
                + "VALUES (" + 
                
                get_headquarter_id()
                
                + "," +
                
                "'" + descripcio_text.getText() + "'"
                
                + "," +
                
                "'" + data_text.getText()+ "'"
                
                + "," +
                                
                Double.valueOf(mov_textfield.getText())+
                
                ");";
        
        System.out.println(sql);
        try {
            
            stmt = con.createStatement();          
        
            stmt.executeUpdate(sql);
            
            JOptionPane.showMessageDialog(this, "S'ha afegit correctament!", "Status", JOptionPane.INFORMATION_MESSAGE);
            
        } catch (SQLException e){
            
            JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);           
            
        }
    }
    
    
    private void carregar_headquarters(){
        ResultSet res = executeQuery(con, "SELECT headquarterid, headquartername FROM headquarters;");
        loadBranches(res,head_combobox);
        
    }
    
    
    
    private ResultSet executeQuery (Connection con, String query){
        
        try {
        
            stmt = con.createStatement();
            
            rs = stmt.executeQuery(query);           
            
            return rs;
        
        } catch (SQLException e){
          
            //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
            
            return null;
        }
    }
    
    private void loadBranches(ResultSet rs_o, javax.swing.JComboBox<String> in ){       
        in.removeAllItems();
        
        try {
            ResultSetMetaData rsmd = rs_o.getMetaData();
            int columnas = rsmd.getColumnCount();
            while ( rs_o.next() ) {  
                String result = "";
                for (int i = 1; i < columnas; i++){
                    result = result+rs_o.getString(i)+", ";
                }
                result = result+rs_o.getString(columnas);
               in.addItem(result);                        
               
            }  
        } catch (SQLException e){
            
             //JOptionPane.showMessageDialog(this, e.getMessage(), "Status", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    private int get_headquarter_id(){
        StringTokenizer st = new StringTokenizer(head_combobox.getSelectedItem().toString(),",");
        return Integer.valueOf(st.nextToken());
    }
    
    private void comprovar(){
        affegir_button.setEnabled(revisar());
    }
    
    private boolean revisar(){
        if (descripcio_text.getText().isBlank()){
            return false;
        }
        
        if (mov_textfield.getText().isBlank()){
            return false;
        }
        if (!mov_textfield.getText().isBlank()){
            try {
                int numero = Integer.parseInt(mov_textfield.getText());
                
                if (1 > numero){
                    return false;
                }
            } catch (NumberFormatException e){
                return false;
            }
        }
        return true;
    }
}
